### ISSUE TITLE
Java: debugging JUnit tests

### ISSUE THREAD

**Issue by takase1121** [daveleroy/sublime_debugger#180]
I can't figure out a way to debug a JUnit test. I use JUnit 5 as a standalone jar file and I can't figure out how to launch it.

I went and poke around nvim-jdtls' code to find that there's a command to get the appropriate JUnit test command to run (which you can later attach to) but I have no idea how that would work with sublime debugger.

Here's the relevant nvim-jdtls command:

https://github.com/mfussenegger/nvim-jdtls/blob/cc59c194b3c6371e940b8aba9146a068b8035dee/lua/jdtls.lua#L256-L267

**Comment by LDAP** [comment]
The Java Debug Adapter is special in that it requires communication with the LSP-side. There might be work necessary in LSP-jdtls in addition to support JUnit in Sublime Debugger.

**Comment by LDAP** [comment]
Fixed with the latest release. This can be closed @daveleroy

**Comment by appelgriebsch** [comment]
hmmm still facing the issue when trying to run any kind of JUnit tests via LSP-jdtls with the debugger open...

```
Unable to start adapter: Unable to connect to LSP client (timed out)
```

**Comment by LDAP** [comment]
Can you post your ST console log and LSP log?

**Comment by daveleroy** [comment]
This might just be timing out I think the timeout is something short like 2.5 seconds which could be increased

**Comment by appelgriebsch** [comment]
> This might just be timing out I think the timeout is something short like 2.5 seconds which could be increased

Yeah, that sounds like it. Any hint how I can extend the timeout in my setup (just to cross check)?

**Comment by LDAP** [comment]
Open your Packages directory. Then edit this line https://github.com/daveleroy/sublime_debugger/blob/master/modules/adapters/util/lsp.py#L25 in the Debugger package. Then restart ST.
